### ISSUE TITLE
Won't poll from automation if disable auto API polling is selected

### ISSUE THREAD

**Issue by Mista-P** [oziee/ha-solcast-solar#118]
### The problem

If you disable auto API polling via the configure option (to reduce unnecessary API polls) you cannot invoke a timed poll via automation. 

### What version of Solcast Integration has the issue?

v3.0.45

### What version of Home Assistant are you using?

2023.3.6

**Comment by Mista-P** [comment]
automation as per example :- Basic HA Automation to manual config Solcast API data:

**Comment by oziee** [comment]
what's in the logs?? errors?? helpful information like Api limit calls reached??

**Comment by Mista-P** [comment]
Fresh install (not upgraded)  
Logging API limit reached.

Since then I have commented out line 52-55 in coordinator.py  
and 
added in
 
if self._autopollingdisabled:
            _LOGGER.debug("SOLCAST - Auto poll the Solcast API for data is disabled.")
            return None

at the top of update_forecast (line 123).. 
Just retesting today as the 24 hrs 12 API limit is very frustrating with two roof strings.

**Comment by Mista-P** [comment]
testing so far looks today good ..

**Comment by oziee** [comment]
since you have changed the code file any information is would invalid for me to be able to follow along and provide assistance.
if auto polling is disabled the integration already debug logs out if its enabled or not

not sure where you are getting a 12 API limit from.. old Solcast cast members have 50 api limit and new users only get 10
with two roof top sites in the one account you only get 5 api calls to get data for both sites.
If you create a second solcast account and have one rooftop site in each account you can add both the api keys to the integration allowing for 10 api calls for each rooftop
in the integration config you comma seperate the api keys to add more accounts
KEY=xxxxxxxxxxxxxx,yyyyyyyyyyyy

**Comment by Mista-P** [comment]
I had an old account which only had one string available so reached out to support but never got a response .. so created a new account with a 10API limit ... The auto polling in the HA plugin after sun up will use  2 x API (two strings) calls per hour so by early morning you just get 'API limit reached'. 
My use case is for tomorrow's forecast to charge batteries overnight from the grid. I know my house total KWh requirements so will import cheap overnight power to supplement the next days solar generation if it falls short. 

Thx for the tip on the API keys .. Did't know that :)
