### ISSUE TITLE
HACS Plugin not found

### ISSUE THREAD

**Issue by pschraml** [oziee/ha-solcast-solar#128]
### The problem

I tried to deploy ha-solcast-solar via HACS link in your description  but when I get redirected the plugin is not in the HACS repository the link I get redirected is https://my.home-assistant.io/redirect/hacs_repository/?owner=oziee&repository=ha-solcast-solar&category=plugin

I get the error message Repository oziee/ha-solcast-solar not found

Hope that can be fixed easy.

### What version of Solcast Integration has the issue?

N/A not installed yet

### What version of Home Assistant are you using?

Home Assistant 2023.5.3 

### Diagnostics information

No diagnostic

### Logs debug/info/error output

```txt
NO debug
```

### Additional information

N/A

**Comment by oziee** [comment]
Do you have HACS installed?

**Comment by jevburchell** [comment]
I am also having this same issue.  I have HACS installed.

I have also tried copying the latest release into my custom_components folder.  There is no integrtation available after that when I search for it in devices & services nor HACS

**Comment by GrogSym** [comment]
Snap!

**Comment by jevburchell** [comment]
I got it working by installing an older version - v3

**Comment by oziee** [comment]
I have no idea what your doing or seeing, but this isn't a issue with the integration

**Comment by jevburchell** [comment]
> I have no idea what your doing or seeing, but this isn't a issue with the integration

It definitely is I'm afraid.  I've both installed and used your integration on previous HA installations so I know the procedure.  Your latest version does not install correctly, and multiple people are seeing the same bug.

I had a previous download still on my pc which is why I was able to install - but there is an issue with your latest version which prevents it being visible as an integration after copying files to custom_components.

We are here to provide you with whatever info you need to address the issue
