### ISSUE TITLE
Time seems shifted

### ISSUE THREAD

**Issue by mahmoud-os93** [oziee/ha-solcast-solar#144]
### The problem

My time vs current expected kwh seems shifted as seen in the image, my timezone in HA is correct, any way to correct this ? or do you think it's an issue with polling interval ?
![image](https://github.com/oziee/ha-solcast-solar/assets/85693689/75dc8ec7-c701-49a6-b08d-8c5d8985ce5a)

Big Thanks !

### What version of Solcast Integration has the issue?

v3.0.47

### What version of Home Assistant are you using?

2023.06.2

### Logs debug/info/error output

```txt
My time vs current expected kwh seems shifted as seen in the image, my timezone in HA is correct, any way to correct this ? or do you think it's an issue with polling interval ?
![image](https://github.com/oziee/ha-solcast-solar/assets/85693689/75dc8ec7-c701-49a6-b08d-8c5d8985ce5a)
```

**Comment by oziee** [comment]
this type of question has been asked so many times before.. it usually turns out to be either 
- HA timezone is incorrect 
- the local machine its running on timezone problem
- or just that it is correct and that your solar panels in the morning are not performing to the graphs prediction

Anyways.. I am currently coding some changes that may eliminate timezone errors so will see.. still testing it here

**Comment by mahmoud-os93** [comment]
> 

Thanks ! I actually checked the time settings before. Might be the third issue..
It would be a nice idea to configure a damping factor for sunrise/sunset or a shift in time prediction.
Big Thanks for your work !

**Comment by oziee** [comment]
@mahmoud-os93 HA 2022.7 has a new setting in the user account that allows for timezone info.. this might be something to check

https://youtu.be/KCBExUoMZEY?t=350

**Comment by jon-riches** [comment]
Thanks for your time spent on this oziee

Time looks shifted to me too, my timezone is correct is HA

My system is set at UK time (GMT + 00:00, London) currently actually GMT + 1 due to BST, and sensor.time is 11:52 (correct) when I grabbed the following. Terminal also shows the correct time.

Forecast this hour is 2908, but if I look at the attributes for forecast today 2908 is the figure for next hour and not this:

- period_start: '2023-07-16T09:00:00+01:00'
  pv_estimate: 2.0365
- period_start: '2023-07-16T10:00:00+01:00'
  pv_estimate: 2.5233
- period_start: '2023-07-16T11:00:00+01:00'
  pv_estimate: 2.9082
- period_start: '2023-07-16T12:00:00+01:00'
  pv_estimate: 3.25125

Am I missing something, or is it a bug?

Kind regards

Jonathan

**Comment by oziee** [comment]
Really would be good if I could see the data that Solcast returns to see what's  going on.. is it me changing some time or the Solcast time is off

**Comment by jon-riches** [comment]
Sorry for the delay, hopefully this helps. I've just grabbed the JSON from the website, and called the HA service to update Solcast.
This is an extract from sensor.forecast_tomorrow:
```
- period_start: '2023-07-28T05:00:00+01:00'
  pv_estimate: 0
  pv_estimate10: 0
  pv_estimate90: 0
- period_start: '2023-07-28T05:30:00+01:00'
  pv_estimate: 0.0131
  pv_estimate10: 0.00585
  pv_estimate90: 0.0171
- period_start: '2023-07-28T06:00:00+01:00'
  pv_estimate: 0.04955
  pv_estimate10: 0.02475
  pv_estimate90: 0.0520275
- period_start: '2023-07-28T06:30:00+01:00'
  pv_estimate: 0.11465
  pv_estimate10: 0.05335
  pv_estimate90: 0.1203825
- period_start: '2023-07-28T07:00:00+01:00'
  pv_estimate: 0.211
  pv_estimate10: 0.1037
  pv_estimate90: 0.22155
```
and this is an extract from an API call at ~ the same time:
```
       {
            "pv_estimate": 0,
            "pv_estimate10": 0,
            "pv_estimate90": 0,
            "period_end": "2023-07-28T04:30:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.0262,
            "pv_estimate10": 0.0117,
            "pv_estimate90": 0.0342,
            "period_end": "2023-07-28T05:00:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.0991,
            "pv_estimate10": 0.0495,
            "pv_estimate90": 0.104055,
            "period_end": "2023-07-28T05:30:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.2293,
            "pv_estimate10": 0.1067,
            "pv_estimate90": 0.240765,
            "period_end": "2023-07-28T06:00:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.422,
            "pv_estimate10": 0.2074,
            "pv_estimate90": 0.4431,
            "period_end": "2023-07-28T06:30:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.6119,
            "pv_estimate10": 0.2983,
            "pv_estimate90": 0.642495,
            "period_end": "2023-07-28T07:00:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.8063,
            "pv_estimate10": 0.3664,
            "pv_estimate90": 0.9708,
            "period_end": "2023-07-28T07:30:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 1.0034,
            "pv_estimate10": 0.4581,
            "pv_estimate90": 1.3967,
            "period_end": "2023-07-28T08:00:00.0000000Z",
            "period": "PT30M"
        }
```
At first I was completely lost as to why they are totally different, and then I realised this:
```
- period_start: '2023-07-28T05:30:00+01:00'
  pv_estimate: 0.0131
  pv_estimate10: 0.00585
  pv_estimate90: 0.0171
- period_start: '2023-07-28T06:00:00+01:00'
  pv_estimate: 0.04955
  pv_estimate10: 0.02475
  pv_estimate90: 0.0520275
```
Is exactly half of this:
```
        {
            "pv_estimate": 0.0262,
            "pv_estimate10": 0.0117,
            "pv_estimate90": 0.0342,
            "period_end": "2023-07-28T05:00:00.0000000Z",
            "period": "PT30M"
        },
        {
            "pv_estimate": 0.0991,
            "pv_estimate10": 0.0495,
            "pv_estimate90": 0.104055,
            "period_end": "2023-07-28T05:30:00.0000000Z",
            "period": "PT30M"
        },
```
Which I'm assuming is because on is kWh, and the other is kW
So in this case 
period_start: '2023-07-28T05:30:00+01:00' is being equated to "period_end": "2023-07-28T05:00:00.0000000Z"

Which I think is wrong?
"period_end": "2023-07-28T05:00:00.0000000Z" equates to a period start of ": "2023-07-28T04:30:00.0000000Z"

Or maybe I'm just losing the plot!

**Comment by oziee** [comment]
it does halve the value as yes its converting to kWh as each solcast item is 30min

I am working on just removing a lot of converting data from the solcast data and seeing if this helps others.. might be a bit before I release it

**Comment by oziee** [comment]
there is a pre release v3.1.0
I am hoping this will solve or help even more to find out why there is a time shift in the energy graph for some.
let me know how this pre release goes for all here and what you now see 

There is a greater in depth "download diagnostics" with more info to narrow down what the data holds to what HA draws
<img width="1296" alt="Screenshot 2023-08-01 at 11 17 38 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/aa2af101-f2ec-4637-a5cc-c73066ca3436">

**Comment by theRoundGreek** [comment]
Same issue here.
![image](https://github.com/oziee/ha-solcast-solar/assets/26344577/95d68ee8-b9e0-456c-b00b-8bb577ed2213)


[config_entry-solcast_solar-6bc040881666080409cfff1502457914.json (1).txt](https://github.com/oziee/ha-solcast-solar/files/12237850/config_entry-solcast_solar-6bc040881666080409cfff1502457914.json.1.txt)

**Comment by oziee** [comment]
Did u read the above info?? 
Try the new pre release
