### ISSUE TITLE
Forecast Today no longer shows the days forecast 

### ISSUE THREAD

**Issue by gedger** [oziee/ha-solcast-solar#159]
### The problem

If HA is reset during the day then Forecast Today shows the same as Forecast Remaining Today rather the the actual total daily forecast

### What version of Solcast Integration has the issue?

3.1.4

### What version of Home Assistant are you using?

2023.7.3

### Diagnostics information

[config_entry-solcast_solar-8ddf716142516158525d1e9fba683025.json.txt](https://github.com/oziee/ha-solcast-solar/files/12327610/config_entry-solcast_solar-8ddf716142516158525d1e9fba683025.json.txt)

### Logs debug/info/error output

```txt
No error generated
```

**Comment by no1knows** [comment]
+1 I'm seeing the same.

**Comment by oziee** [comment]
Ahh yes.. well the data has changed so when updating the integration say at 2pm it only has the data from Solcast from 2pm onwards 

Tomorrow it will all look fine

**Comment by rany2** [comment]
@oziee Because you don't get the actuals anymore (and most users never updated them anyway), maybe it is a good idea to keep track of the previous data in the JSON file you use for persistence. This is what I've done in the version I use internally, you can limit the size automatically with `deque` from python collections, just specify `maxlen` as argument to it and keep enough data so these sensors keep working as expected.

**Comment by oziee** [comment]
It's annoying that the Solcast data isn't full days, would make things so easy 😄 
Problem is the old json file included converted utc times and now it doesn't so using the old data and mixing in the new would not work

Basically the Aussie saying here is "too bad" "it is what it is" 😀 

If it been working fine for ppl staying in the older v3 is just fine
