### ISSUE TITLE
Hourly estimates are not aggregated across multiple accounts

### ISSUE THREAD

**Issue by ffm777** [oziee/ha-solcast-solar#170]
### The problem

I'm using the Solcast integration with 2 accounts at Solcast, because I have 4 planes on my roof. Since the latest version (3.1) the hourly forecasts (contained as attributes in sensor.solcast_forecast_*) are not correctly aggregated across multiple accounts. The total, which is the sensor value, is correctly aggregated across the 2 accounts. But not the hourly forecasts.

### What version of Solcast Integration has the issue?

v3.1.6

### What version of Home Assistant are you using?

2023.8.2

### Logs debug/info/error output

```txt
No specific error message is shown as the integration works fine, it's just that the hourly forecasts are not correct.
```

**Comment by ffm777** [comment]
I just saw the later comments in https://github.com/oziee/ha-solcast-solar/issues/153, where a user reports the values in the hourly forecasts to be halved. That could be related. So maybe it is the same issue. In my case it first appeared to be an aggregation issue across the accounts, but since my planes are all similar in size, this could also be the "halved values" issue reported in the issue mentioned above.

**Comment by purcell-lab** [comment]
> I just saw the later comments in #153, where a user reports the values in the hourly forecasts to be halved. That could be related. So maybe it is the same issue. In my case it first appeared to be an aggregation issue across the accounts, but since my planes are all similar in size, this could also be the "halved values" issue reported in the issue mentioned above.

Just a clarification,  solcast used to provide attributes for _forecasts_ which were hourly and _detailedForecasts_ that were every thirty minutes.  Currently solcast integration is reporting the _detailedForecasts_, which are not halved they are just the energy (kWh) forecast in 30 minute periods.

My system is currently putting out a maximum of around 10 kW at midday and the peak forecast sensor shows this correctly:

![image](https://github.com/oziee/ha-solcast-solar/assets/79175134/380a6470-15a7-4c33-a80b-71dab63c2f3a)

The forecast today energy (kWh) attributes are only for 30 minute windows so that is why they appear to be half the actual power (kW) value.

![Screenshot 2023-08-17 18 30 54](https://github.com/oziee/ha-solcast-solar/assets/79175134/ea3b776a-39be-41ba-a69e-4b21321cbcd8)

So in my case today 5.3054 kWh (12:00-12:30) + 5.2845 kWh (12:30-13:00) = 10.58 kWh (12:00-13:00) .

It would also help if you posted your actual values from solcast and home assistant sensors.

**Comment by ydestord** [comment]
I had the same issues, due to the energy now being reported in slots of 30 minutes. I had an Apexchart that was showing the predicted value of the current & next day and these showed half of the forecasted production.   

My workaround was to use an aggregate function in Apexchart

  - entity: sensor.solcast_forecast_today
    name: PV_estimate_10
    stroke_width: 2
    extend_to: now
    color: '#960da0'
    data_generator: |
      return entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]), entity.attributes.detailedForecast[index]["pv_estimate10"] ];
      });
    group_by:
      func: sum
      duration: 60min

This corrected the graph for me

**Comment by oziee** [comment]
Hard to make anyone happy lol

Ppl wanted 30min for whatever reason.. I have changed the code back to hourly, but it's just in the file and not packed into a release.. you can just change the file manually for now if ppl want

**Comment by kds69** [comment]
I’m confused: detailedForecast can be kept as is with 30mn, what we are missing is Forecast which indeed used to be available and aggregated against 1h time slots.
Am I missing the point ?

**Comment by ffm777** [comment]
Thanks for all the comments. Since I just want a forecast of the kW and not the kWh, I solved the problem by just multiplying the 30-minute kWh forecast by 2. Works fine for me.

**Comment by purcell-lab** [comment]
> hoping to expand it for more options s but can then remove attributes from sensors

please consider that many people rely on those attributes to use in templates, if you are proposing to switch to services functions data returns I would be happy to assist with testing.

I'm using EMHASS for my home energy management system and feed it the solar forecasts directly from your attributes:

```
        "pv_power_forecast": {{
          ([states('sensor.APF_Generation_Entity')|int(0)] +
          state_attr('sensor.solcast_forecast_today', 'detailedForecast')|selectattr('period_start','gt',utcnow()) | map(attribute='pv_estimate')|map('multiply',2000)|map('int')|list +
          state_attr('sensor.solcast_forecast_tomorrow', 'detailedForecast')|selectattr('period_start','gt',utcnow()) | map(attribute='pv_estimate')|map('multiply',2000)|map('int')|list
          )| tojson
        }},
```

https://community.home-assistant.io/t/emhass-an-energy-management-for-home-assistant/338126/1078?u=markpurcell

**Comment by oziee** [comment]
just roll back to v3.0.x
