### ISSUE TITLE
Historical data seems to no longer be available

### ISSUE THREAD

**Issue by springfall2008** [oziee/ha-solcast-solar#171]
### The problem

The Energy dashboard used to show the predicted solar production vs the actual historically but it now only seems to show the current day forward. Not sure if this relates to a change to solcast plugin or something else?

### What version of Solcast Integration has the issue?

v3.1.5

### What version of Home Assistant are you using?

2023.8.1

### Diagnostics information

![image](https://github.com/oziee/ha-solcast-solar/assets/48591903/18612060-0d38-4f35-b359-7df4a02348ac)

### Logs debug/info/error output

```txt
n/a
```

**Comment by oziee** [comment]
If you just updated to v3 there is no longer past actual data being called

If you have recorder enabled then the last 1000 days (if you have that much enabled) will load

**Comment by treforsouthwell-sifive** [comment]
Hi Oziee,

I'm not sure I understand what you are saying, do I need to enable something in HA to have the past data again? I have the normal HA recording enabled (actually set to 30 seconds) but I've not set up anything specific for Solcast.

**Comment by treforsouthwell-sifive** [comment]
I just checked today and the past data is still not being logged, only today. What do I need to change?

**Comment by rany2** [comment]
@treforsouthwell-sifive What is your forecast this hour sensor called? As a workaround, if it's not `sensor.forecast_this_hour` rename it to `sensor.forecast_this_hour`.

@oziee The issue is that you are relying on a fixed sensor name to get the data for the dashboard, what if the name was `sensor.forecast_hour_2` or something of that sort? I think it's better to just put in some wh_hours dict in solcast.json and pull from that. I already added that option so you could copy it over, include adding an option to keep N days so the solcast.json doesn't explode in a few years, etc.

**Comment by oziee** [comment]
just roll back to v3.0.x
