### ISSUE TITLE
System Log Error `unable to get sensor value Solcast data didn't return anything within`

### ISSUE THREAD

**Issue by Melonostrorog** [oziee/ha-solcast-solar#180]
### The problem

No value for forecast production today. In addition, several errors visible in the logs.

### What version of Solcast Integration has the issue?

4.0.2

### What version of Home Assistant are you using?

2023.8.4

### Diagnostics information

[home-assistant_solcast_solar_2023-09-03T16-34-22.265Z.log](https://github.com/oziee/ha-solcast-solar/files/12506575/home-assistant_solcast_solar_2023-09-03T16-34-22.265Z.log)

### Logs debug/info/error output

```txt
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:378
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 18:06:00 (33 occurrences)
Last logged: 18:38:00

SOLCAST - unable to get sensor value Solcast data didn't return anything within 1:00:00 (needed_delta=15:59:59) Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 374, in _handle_coordinator_update self._sensor_data = self.coordinator.get_sensor_value( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 142, in get_sensor_value return self.solcast.get_total_kwh_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 413, in get_total_kwh_forecast_day raise ValueError( ValueError: Solcast data didn't return anything within 1:00:00 (needed_delta=15:59:59)

Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:382
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 18:06:00 (33 occurrences)
Last logged: 18:38:00

SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 17 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 195, in get_sensor_extra_attributes return self.solcast.get_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 17
```

**Comment by oziee** [comment]
ok so this message is telling me that the Solcast data does not contain enough data.. its missing one item either 15:00 or 15:30 from Solcast

was this a new install?? and update install ??

can you click the three dots(shown below) and click `Download diagnostics` data and up it here?
<img width="440" alt="Screenshot 2023-09-04 at 8 50 57 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/a1a9eb9a-b6a7-461b-bc2c-930b325cb0bc">

that will help see what might have gone wrong

**Comment by oziee** [comment]
I see this at my end too.. I am trying to work out why data is missing.. is it sorted/filtered code for the data.. or is it because sometimes when you poll the Solcast API near or on the hour or half hour their data is not always ready right on the minute x:00:00:00 or x:03:00:00 and it can return with the first value or misses it because its still updating

**Comment by rany2** [comment]
@oziee its because you aren't getting historic data when there is data missing for the current day. When you added that code it works for me because I'm always getting historic and forecast data, but you are never getting historic data as far as I know.

I advise that if you are missing data for current day, you use up an extra api call to get historic data. I think it should be straightforward as you already have a routine where you get the current tally for the day, you just have to make sure its 48 data points (or 24 depending on how you're doing this). If its not, just get the old data.

**Comment by oziee** [comment]
@rany2 I am.. the very first time the integration runs its getting the past data and future..

its users that write when its the tomorrow or D1 sensors that is a problem.. that would be where the marriage of the past and future is missing one 30min slot solcast api is depending on the time run

I keep seeing the error on the Day 7 sensors where it only has 34 items and not 48 for a whole day.. and this happens at midnight because I have not called the api update since sun down so getting 168 (max solcast points to get) does not include enough data for day 7 until sun up that morning when it polls for data that will include it

So D7 is obvious how that can fail depending on when and how often users poll for data..its when its tomorrow or d1 where there should be no missing items.. if the past/future call was missing it would miss data right at the time of the api call for 'today'

**Comment by pvprodk** [comment]
Just want to let you know that today I am getting data for "Forecast Today"

![image](https://github.com/oziee/ha-solcast-solar/assets/79306514/eb85cf1f-3490-4819-a334-58be3a0346fe)

**Comment by membersound** [comment]
I have the same issue: all sensors work except "Forecast Today". Which is bad, because that's the one sensor that I need...

**Comment by oziee** [comment]
> I have the same issue: all sensors work except "Forecast Today". Which is bad, because that's the one sensor that I need...
tomorrow it will be fine

**Comment by JIBYC** [comment]
Hi

Appreciate this issue is closed but I also getting Unknown or 0.00kWh for all sensors as of yesterday morning.

**Comment by oziee** [comment]
Update to 4.0.3

**Comment by JIBYC** [comment]
Done so and carried out a full reinstall.

**Comment by membersound** [comment]
Can confirm the fix works great!
