### ISSUE TITLE
"Forecast remaining today" not calculated correctly

### ISSUE THREAD

**Issue by DragonQ** [oziee/ha-solcast-solar#193]
### The problem

Since the update to v4.0, I have noticed the "forecast remaining today" value is not correct. This is obvious from the fact that near the end of the day (say 17:01), the "Solcast PV Forecast Forecast Remaining Today" value is always _lower_ than the "Solcast PV Forecast Forecast This Hour" value, which doesn't make any sense. e.g. this evening, "Solcast PV Forecast Forecast Remaining Today" was 0.23 kWh at 17:01, yet "Solcast PV Forecast Forecast This Hour" for 17:00-18:00 was 0.48 kWh and for 18:00-19:00 it was 0.13 kWh

This wasn't the case in v3.x so something in v4.x has definitely broken this calculation.

### What version of Solcast Integration has the issue?

v4.0.4

### What version of Home Assistant are you using?

2023.9.1

### Logs debug/info/error output

```txt
N/A
```

**Comment by oziee** [comment]
ill have a look at this.. off the top of my head since all the data is in 30min intervals, then at 17:01 it might be reporting data 17:30 ->

so not including the data value for 17:00 - 17:30

if the data was in 5min intervals then remaining would calc differently.. just guessing till it gets later here and I can see myself on my system

**Comment by oziee** [comment]
see how 4.0.5 goes tomorrow

**Comment by DragonQ** [comment]
Still not quite right with 4.0.5. Example:

At 17:00, remaining changed to 0.3 kWh. However, this hour was 488 Wh, next hour was 90 Wh, hour after that was 8 Wh, so 0.586 kWh total.

**Comment by oziee** [comment]
think 4.0.6 fixes it now
