### ISSUE TITLE
Add damping factor

### ISSUE THREAD

**Issue by home409ca** [oziee/ha-solcast-solar#204]
### The problem

The damping factor allows you to adjust and “damp” the results of your solar predictions in the morning and evening a bit and is a great method to make results less optimistic and more tuned to your reality.

### What version of Solcast Integration has the issue?

4.0.7

### Logs debug/info/error output

```txt
n/a
```

**Comment by oziee** [comment]
Did

This has been asked before.. it is not something I am considering adding.

This would be because it's too variable an option and everyone's needs would be too varied.. 

- dampen just the morning, just the evening, dampen both
- dampen from time X-Y
-dampen by x%.. is that both times our x% morning and y% arvo

Too many things to control for too many use cases and no one would be happy :)

So what could you do..
Well you could create a template sensor that uses the value from the integration, and with that you can create your own requirements in if between x time dampen by X factor and then use that template sensor for your needs

**Comment by home409ca** [comment]
Can you add a table where you can manually determine the coefficient? Then everyone can listen as they wish at selected times.

Example:

| Hour | Factor |
|------|--------|
|  0   |   1    |
|  1   |   1    |
|  2   |   1    |
|  3   |   1    |
|  4   |   1    |
|  5   |  0,8   |
|  6   |  0,8   |
|  7   |  0,8   |
|  8   |   1    |
|  9   |   1    |
|  10  |   1    |
|  11  |   1    |
|  12  |   1    |
|  13  |   1    |
|  14  |   1    |
|  15  |   1    |
|  16  |  0,6   |
|  17  |  0,6   |
|  18  |  0,6   |
|  19  |  0,6   |
|  20  |   1    |
|  21  |   1    |
|  22  |   1    |
|  23  |   1    |

**Comment by oziee** [comment]
ATM no..
But it is something you can do with a template sensor yourself right now and use it

**Comment by oziee** [comment]
Let me think on this more

**Comment by home409ca** [comment]
> ATM no.. But it is something you can do with a template sensor yourself right now and use it

I don't know how to create such a sensor. Because then you have to change the attributes in the forecasts for the next days and change the data used by the "energy" panel somewhere.

This is too difficult for me. I'm not a programmer...

> Let me think on this more

thanks! It'd be great

**Comment by oziee** [comment]
hmmm???? :)

<img width="368" alt="Screenshot 2023-09-30 at 11 20 16 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/23d5588b-7628-46ab-b5c5-cfd30701cd44">
