### ISSUE TITLE
API count showing unavailable

### ISSUE THREAD

**Issue by snigehere** [oziee/ha-solcast-solar#309]
### The problem

After installing Version: v4.0.23 "API Limit" and "API Used" show as "Unavailable".  I don't know if this is caused by a change in the app or if its an new issue.

As I have done a number of restarts and runs of the API today to modify my automation to be random I had already used up all my calls before I installed the new version.

I had expected the count to persist across version updates.
"API Last Polled" correctly shows "5 hours ago" so that value has persisted.

The log shows that the API count was updated at the same time as the last polled value

30 May 2024 Solcast PV Forecast API Last Polled changed to 30 May 2024 at 12:02
12:02:40 - 5 hours ago API Used changed to 10
12:02:40 - 5 hours ago Solcast PV Forecast API Last Polled changed to 30 May 2024 at 11:36
11:36:42 - 5 hours ago API Used changed to 8
11:36:42 - 5 hours ago Solcast PV Forecast Peak Time Tomorrow changed to 31 May 2024 at 10:00
11:36:42 - 5 hours ago Solcast PV Forecast API Last Polled changed to 30 May 2024 at 10:00
10:00:11 - 7 hours ago API Used changed to 6

### What version of Solcast Integration has the issue?

v4.0.23

### What version of Home Assistant are you using?

2024.5.5

### Diagnostics information

[config_entry-solcast_solar-5dd1ed459d5dab6698e2270ea7b6972b.json](https://github.com/oziee/ha-solcast-solar/files/15502321/config_entry-solcast_solar-5dd1ed459d5dab6698e2270ea7b6972b.json)

### Logs debug/info/error output

```txt
due to multiple restarts I don't have the logs for the last run .. i hope that the detail provided allows sufficient information.
```

**Comment by Bighton** [comment]
The release notes contain the answer to your question 

"for now removed the api counter sensors.. one less api endpoint that might cuse 429 status"

**Comment by snigehere** [comment]
hmmm ... thanks - thats a bit of a pain as I use the count to stop the fetch running when I have no slots left ... I guess I just have to leave it running regardless...

**Comment by pspot2** [comment]
@oziee was there any evidence that the API usage endpoint is part of the 429 problem? Those sensors were convenient and valuable because that quota data came directly from the vendor (meaning that it will automatically update in users' dashboards and automations if the vendor decides to change it). While it should be possible to replicate a local static version of those sensors, would a better solution be to make the usage endpoint communication configurable? For example, by using the service's 'data' parameter. The logic behind this would be the following: the default setting would be "off" for those who rarely look at their configs and do not randomize poll times. Those who randomize well might want to turn the usage data on and see whether it works well for them in terms of 429. As an additional measure, there could be a configurable random delay between `sites_data` and `sites_usage`.
