### ISSUE TITLE
Upgrade to HomeAssistant 2022.6 beta release breaks SolCast

### ISSUE THREAD

**Issue by purcell-lab** [oziee/ha-solcast-solar#39]
After upgrade to the next beta SolCast breaks:
https://rc.home-assistant.io/blog/2022/05/25/release-20226/

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:492
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 7:44:57 AM (3 occurrences)
Last logged: 7:44:57 AM

get_forecast_sensor_state: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 432, in get_forecast_sensor_state event_s: list[int] = [event.event_data for event in events] File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2896, in __iter__ return self._iter().__iter__() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter result = self.session.execute( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1695, in execute conn = self._connection_for_bind(bind) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind return self._transaction._connection_for_bind( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind conn = bind.connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect return super(Engine, self).connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect return self._connection_cls(self, close_with_result=close_with_result) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__ else engine.raw_connection() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect return fn() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect return _ConnectionFairy._checkout(self, self._fairy) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout rec = pool._do_get() File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get check_loop( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop raise RuntimeError( RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(
get_forecast_sensor_state: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 482, in get_forecast_sensor_state event_s: list[int] = [event.event_data for event in events] File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2896, in __iter__ return self._iter().__iter__() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter result = self.session.execute( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1695, in execute conn = self._connection_for_bind(bind) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind return self._transaction._connection_for_bind( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind conn = bind.connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect return super(Engine, self).connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect return self._connection_cls(self, close_with_result=close_with_result) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__ else engine.raw_connection() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect return fn() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect return _ConnectionFairy._checkout(self, self._fairy) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout rec = pool._do_get() File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get check_loop( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop raise RuntimeError( RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(
get_forecast_sensor_state: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 457, in get_forecast_sensor_state event_s: list[int] = [event.event_data for event in events] File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2896, in __iter__ return self._iter().__iter__() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter result = self.session.execute( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1695, in execute conn = self._connection_for_bind(bind) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind return self._transaction._connection_for_bind( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind conn = bind.connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect return super(Engine, self).connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect return self._connection_cls(self, close_with_result=close_with_result) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__ else engine.raw_connection() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect return fn() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect return _ConnectionFairy._checkout(self, self._fairy) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout rec = pool._do_get() File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get check_loop( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop raise RuntimeError( RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(

**Comment by purcell-lab** [comment]
Issues still present with upgrade to 2022.6.0b1

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:622
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 9:00:06 AM (2 occurrences)
Last logged: 10:00:07 AM

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 581, in update_forecast foundcount = len(found.all()) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2768, in all return self._iter().all() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter result = self.session.execute( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1695, in execute conn = self._connection_for_bind(bind) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind return self._transaction._connection_for_bind( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind conn = bind.connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect return super(Engine, self).connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect return self._connection_cls(self, close_with_result=close_with_result) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__ else engine.raw_connection() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect return fn() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect return _ConnectionFairy._checkout(self, self._fairy) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout rec = pool._do_get() File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get check_loop( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop raise RuntimeError( RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(
```

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:799
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 8:47:36 AM (4 occurrences)
Last logged: 8:51:53 AM

get_energy_tab_data: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 757, in get_energy_tab_data event_s: list[int] = [event.event_data for event in events] File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2896, in __iter__ return self._iter().__iter__() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter result = self.session.execute( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1695, in execute conn = self._connection_for_bind(bind) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind return self._transaction._connection_for_bind( File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind conn = bind.connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect return super(Engine, self).connect() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect return self._connection_cls(self, close_with_result=close_with_result) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__ else engine.raw_connection() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect return fn() File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect return _ConnectionFairy._checkout(self, self._fairy) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout rec = pool._do_get() File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get check_loop( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop raise RuntimeError( RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(
```

**Comment by oziee** [comment]
im gonna have to work faster on the newer version then :)

**Comment by bdraco** [comment]
I noticed this integration stores data in the events table.   Ideally it would create its own table since doing so slows down everything that needs to read data from that table

**Comment by oziee** [comment]
It's all changed for the next release

**Comment by kcoffau** [comment]
+1 2022.6 Busted Custard.

I know you have it in your next SolCast release.  Just enquiring if you have any thoughts on an expected release?  No rush, just interested.   Thanks for the amazing plugin too!

**Comment by Alllfff** [comment]
Does the non beta 2022.6 also break the integration? It stopped working for me yesterday. Around the same time as I updated to 2022.6 HA Core...

**Comment by markwoodward86** [comment]
> Does the non beta 2022.6 also break the integration? It stopped working for me yesterday. Around the same time as I updated to 2022.6 HA Core...

It appears that it does, i reconfigured to be sure and same thing.

**Comment by Alllfff** [comment]
> It appears that it does, i reconfigured to be sure and same thing. 

Ok good to know I didn't mess something up at my end :)

**Comment by AeroJohnBE** [comment]
@oziee Let us know when you release a newer version of HACS SolCast 😃. We're waiting

**Comment by darek-margas** [comment]
Here is warning from 2022.5.5 which I believe explain issue:
2022-06-04 15:32:58 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for solcast_solar using this method at custom_components/solcast_solar/__init__.py, line 332: event_s: list[int] = [event.event_data for event in events]

**Comment by oziee** [comment]
It ok.. we have known this cause and problem for a long time now.. we all get the same log messages

**Comment by AeroJohnBE** [comment]
Any updates yet?

**Comment by darek-margas** [comment]
> Any updates yet?

I reverted mine to 2022.5.5 and I believe we are waiting for something new so not here.

**Comment by oziee** [comment]
all good things are coming along
<img width="536" alt="Screen Shot 2022-06-08 at 3 53 35 pm" src="https://user-images.githubusercontent.com/1471841/172541966-cb3f84a9-66bd-4f0f-99de-6d3e52cfd2ba.png">

**Comment by oziee** [comment]
who wants to beta test it out?

**Comment by longzheng** [comment]
> who wants to beta test it out?

Yes please. 

P.S. you can publish a "prerelease" release on GitHub.

**Comment by gedger** [comment]
Yes, happy to help.

**Comment by oziee** [comment]
https://github.com/oziee/ha-solcast-solar/releases/tag/v3.0.0

**Comment by oziee** [comment]
> > who wants to beta test it out?
> 
> Yes please.
> 
> P.S. you can publish a "prerelease" release on GitHub.

@longzheng  im guessing that as a pre release HACS does not display this.. and you would need to manually install it?

**Comment by longzheng** [comment]
> > > who wants to beta test it out?
> > 
> > 
> > Yes please.
> > P.S. you can publish a "prerelease" release on GitHub.
> 
> @longzheng im guessing that as a pre release HACS does not display this.. and you would need to manually install it?

Yeah no worries, I didn't use HACS before so I'm just installing manually.

I'm seeing an error after installing and configuring the new one. If I "reload" the integration I see this in the logs

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 5:09:19 PM (1 occurrences)
Last logged: 5:09:19 PM

Error unloading entry NorthRd for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 478, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by oziee** [comment]
@longzheng did you completed delete the old integration first.. then restart HA after changing the files and then recreating the integration again?

**Comment by longzheng** [comment]
Actually it looks like you uploaded an old ZIP file for release 3.0.0?

![image](https://user-images.githubusercontent.com/484912/172554633-ab5f0ed2-8a7b-4fe1-9ca0-58d93f5b9e61.png)

<img width="869" alt="image" src="https://user-images.githubusercontent.com/484912/172554698-ce3a31a4-b7bc-4cc2-aa6b-183c618f40e0.png">

**Comment by longzheng** [comment]
Got an error while setting up

```
2022-06-08 17:20:39 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/solcast_solar/sensor.py", line 115, in async_setup_entry
sen = SolcastSensor(coordinator, SENSORS[sensor_types],entry)
File "/config/custom_components/solcast_solar/sensor.py", line 158, in __init__
self._sensor_data = coordinator.get_sensor_value(entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 124, in get_sensor_value
return self.solcast.get_peak_w_today()
File "/config/custom_components/solcast_solar/solcastapi.py", line 194, in get_peak_w_today
m = max(z['pv_estimate'] for z in g if z)
ValueError: max() arg is an empty sequence
```

**Comment by oziee** [comment]
DOH!!!

**Comment by longzheng** [comment]
I haven't read the code but `get_peak_w_today` makes me assume it's looking at the forecasts for the rest of the day. 

Currently it's the end of the day here so the forecasts for the rest of the day are all 0, not sure if that's the issue.

**Comment by oziee** [comment]
no.. it had my 'test' server ip instead of the solcast api ip

get the files again and try

**Comment by longzheng** [comment]
> no.. it had my 'test' server ip instead of the solcast api ip
> 
> get the files again and try

LOL no wonder it took forever to resolve too 🤣

**Comment by longzheng** [comment]
Looks like I'm stuck for an hour since it's using the cached response

```
2022-06-08 17:32:45 WARNING (MainThread) [custom_components.solcast_solar.coordinator] Solcast - API poll called, but did not happen as the last update is less than an hour old
```

**Comment by oziee** [comment]
just delete the solcast.json file in the config HA dir

**Comment by gedger** [comment]
Just added the latest version and got this.
```
Logger:homeassistant.components.sensor
Source: custom_components/solcast_solar/solcastapi.py:177 
Integration: Sensor (documentation, issues) 
First occurred: 08:33:01 (1 occurrences) 
Last logged: 08:33:01

Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/solcast_solar/sensor.py", line 115, in async_setup_entry
    sen = SolcastSensor(coordinator, SENSORS[sensor_types],entry)
  File "/config/custom_components/solcast_solar/sensor.py", line 158, in __init__
    self._sensor_data = coordinator.get_sensor_value(entity_description.key)
  File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
    return self.solcast.get_forecast_this_hour()
  File "/config/custom_components/solcast_solar/solcastapi.py", line 177, in get_forecast_this_hour
    return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range
```

**Comment by oziee** [comment]
@gedger see above chat.. check the const.py file and make sure the url is the solcast api and not my home computer ip (testing code I forgot to change)

if so download the latest files from here and delete (if there) in the HA config dir solcast.json.. if its not there all ok and restart HA

**Comment by longzheng** [comment]
> just delete the solcast.json file in the config HA dir and restart HA

Thanks, working now.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/484912/172562382-b5afb331-84cb-4594-9553-0f7ea32bfa91.png">

Although I just noticed the "today remaining" sensor no longer seems to be available. It would be great if you could bring that back since that was a super useful metric for me on my dashboard.

**Comment by oziee** [comment]
that should be easy to add

**Comment by Nordicfastware** [comment]
Hi, tested the 3.0.0_beta. Working now.
![image](https://user-images.githubusercontent.com/58825251/172562687-00d7fe9e-506b-45fd-99e2-a0781c9b8393.png)
I think 3 decimals for kWh is overkill. Should be 0 decimal.

And then the problem I have is that it resolves wrongin the forecast curves:
![image](https://user-images.githubusercontent.com/58825251/172563032-5509c212-aa24-4917-ba09-dd67312ff557.png)
 seems to be a factor 100 issue. I have a 6.4 kWp system, should yield say 20-30 kWh. 
 
 Or am I doing something wrong ?

**Comment by gedger** [comment]
Followup, confirmed I have the correct const.py file, deleted solcast.json and rebooted HA. New solcast.json file created and appears to be fully populated with data but still got this logged.
```
This error originated from a custom integration.

Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:102 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 08:45:28 (1 occurrences) 
Last logged: 08:45:28

Solcast - API poll called, but did not happen as the last update is less than an hour old
```

The sensors are populated though and look to be correct values. Will let it run and carry on testing.

**Comment by oziee** [comment]
@gedger that log always shows on HA restart, and just notes that data wasn't pulled from the API because the cached data is still valid and it means its using the cached info.. if it was more than 1 hr then it would poll the api

**Comment by gedger** [comment]
OK, so more of an info message then? So far data looks good, still makes me smile that solcast forecasts to 3 decimal places, if only.....

Thanks for the work on this.

**Comment by SirUli** [comment]
For me the 3.0.0 works flawless - just did the Upgrade via HACS (enabled beta versions) and it worked right away.

**Comment by oziee** [comment]
@SirUli where is this magical enable beta button?? I can't find it

**Comment by SirUli** [comment]
@oziee HACS -> Integrations -> Solcast -> Three dots -> Redownload -> Enable beta -> Select 3.0.0_beta
![image](https://user-images.githubusercontent.com/151354/172575539-4a1e075e-af2d-41d6-bc15-09da370c2f40.png)

**Comment by oziee** [comment]
v3.0.3 beta is out.. fixes a few things and made some changes and added the "forecast remaining today" sensor

**Comment by longzheng** [comment]
> v3.0.3 beta is out.. fixes a few things and made some changes and added the "forecast remaining today" sensor

Thanks. "forecast remaining today" looks good.

**Comment by gedger** [comment]
I just upgraded manually to 3.03 but needed to delete "solcast.json" before it would restart without a list index out of bounds error. Now good, restarts without error.

**Comment by oziee** [comment]
@gedger if you get that error again send me the json file so I can work out what's going on to fix it

**Comment by duffjp** [comment]
Hi,

Just installed this integration and setup as v3.  I don't generally like being on "the latest" tweaked version, I prefer the latest "stable version.  However, I am being told there is an update as v3 is at the bottom of the list as opposed to the top:

![image](https://user-images.githubusercontent.com/103007319/172596454-13f7f9f6-454c-4be0-a207-5da67861fb79.png)

Just wondered if there is a reason that v3 is at the bottom?  Is there a plan to move it to the top at some point in the future, so that update notifications are accurate?

Cheers,

Jon.

**Comment by guybw** [comment]
Just wanted to say thank you so much for fixing this! I use solcast a lot in HA and fixing it so quickly is amazing. You are awesome!

**Comment by daggy72** [comment]
Great Work @oziee !
Beta 3.0.3 works fine now.

Ever considered making it an official integration? Or is that too complicated?

**Comment by markwoodward86** [comment]
Thanks for the fix! Just wondered 8f we can make it so multiple sites per account can be chosen instead of added together? I have two sites but are not the same location.

**Comment by purcell-lab** [comment]
Thanks @oziee fixed..

![image](https://user-images.githubusercontent.com/79175134/172704509-a18adc30-5454-41f2-8155-ff0e193c9efd.png)

**Comment by seblang** [comment]
Hello I have done the update yesterday to v 3.03 and it was working. Since this night after a restart of ha it doesn't work any more. I try to download again the integration but without any success.
 My 12hrlog:
`.  2022-06-08 11:03:10 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-08 11:03:10 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-08 11:03:10 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-08 11:03:10 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-08 11:03:10 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-08 11:03:18 INFO (Thread-5) [homeassistant.components.mqtt.client] Connected to MQTT server mosquitto:1883 (0)
2022-06-08 11:19:48 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.workshop_power or it is/they are currently not available
2022-06-08 12:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 13:00:06 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 14:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 15:00:05 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 16:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 17:00:05 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 18:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 19:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range

2022-06-08 20:00:02 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Exceeded Solcast API allowed polling limit
2022-06-08 20:00:02 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] Solcast fetch_data error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 341, in fetch_data
raise Exception(f"HTTP error: Exceeded Solcast API allowed polling limit")
Exception: HTTP error: Exceeded Solcast API allowed polling limit

2022-06-08 20:00:02 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] Solcast http_data error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 264, in http_data
for x in ae['estimated_actuals']:
TypeError: 'NoneType' object is not subscriptable

2022-06-08 20:00:02 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 122, in get_sensor_value
return self.solcast.get_total_kwh_forecast_today()
File "/config/custom_components/solcast_solar/solcastapi.py", line 195, in get_total_kwh_forecast_today
g = [d for d in self._data["forecasts"] if d['period_end'].date() == da]
TypeError: list indices must be integers or slices, not str

2022-06-08 21:00:00 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 89, in update_forecast
last_update = self.solcast.get_last_updated_datetime() + timedelta(seconds=3500)
File "/config/custom_components/solcast_solar/solcastapi.py", line 118, in get_last_updated_datetime
return dt.fromisoformat(self._data["last_updated"])
TypeError: list indices must be integers or slices, not str
   `

**Comment by AeroJohnBE** [comment]
I also have the same problem
