### ISSUE TITLE
All values show zero, last polling Jan 2000

### ISSUE THREAD

**Issue by TriploidTree** [oziee/ha-solcast-solar#44]
When I look up the Solcast values, they all show as zero and the API was last polled in January 2000

System:
Solcast via HACS, v3.0.5 beta
Home Assistant Core 2022.6.6
Rebooted multiple times

It seems to be accessing the API ok as it pulled my house/solar configuartion no problem but no forecasting data appears.
![solcastBug](https://user-images.githubusercontent.com/4170521/173957802-24fd620e-5320-4be1-b805-a315f1b6f9e8.png)
![bugSolcast](https://user-images.githubusercontent.com/4170521/173957809-bb65431f-d767-4213-86a3-d2783cab4f90.png)

**Comment by TriploidTree** [comment]
Hah, after we rolled past UTC midnight (1am in Ireland at this time of year), it started updating. Might want to add that to the known issues/readme until it can be handled w/o worry.

**Comment by oziee** [comment]
well if you are out of API calls (solcast lets you have 50 free) then the integration is not able to get any data so it just sets 0 and a date way in the past so that any automations etc don't get confused.

solcast reset the api allowance at midnight UTC time so the integration would then have been able to get data.

solcast do not have any api info it retrieve your current api limit use. so it won't know what you use if you deleted the integration over and over either, it just starts counting what it uses and if nothing else is polling your api then the count will be fine
