### ISSUE TITLE
Uploading measurements to solcast

### ISSUE THREAD

**Issue by timbuchwaldt** [oziee/ha-solcast-solar#66]
Via this API https://docs.solcast.com.au/#measurements-rooftop-site solcast allows uploading measurements.
With those the forecasts can be improved and validated. I'm not sure this is feasible/easily doable, but it would be amazing if this integration would support uploading to solcast.

**Comment by tomtom5152** [comment]
Well this is kinda weird, I stumbled across this myself just. I noted there wasn't an issue so thought I'd investigate if it was at least feasible within home-assistant first before I opened one. It's been a while since I've done any python but just about got a dev setup ready, get ready to clone to repo for forking, and notice a new issue which is exactly what I've just started investigating. Will submit any progress here.

**Comment by oziee** [comment]
as per solcast "PV Tuning has now been decommissioned" - https://articles.solcast.com.au/en/articles/2366323-pv-tuning-technology
