### ISSUE TITLE
HA Logs Show update_forecast error on 2022.8

### ISSUE THREAD

**Issue by BettySwallocks** [oziee/ha-solcast-solar#68]
Hi Oziee,

My new implementation of Solcast integration into the recently released HA 2022.8 has a particular error in the log:

`update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 133, in update_forecast for update_callback in self._listeners: RuntimeError: dictionary changed size during iteration`

Can you provide advice or a fix?

**Comment by dcod3d** [comment]
Looks like the same as #56 

It does poll when HA starts up, but not at the hourly poll.

**Comment by godfreym29** [comment]
I'm seeing the same thing.
It only updates on a reboot, but not hourly during the day

**Comment by BettySwallocks** [comment]
OK - I didn't look for existing issues as they were all closed.

**Comment by dcod3d** [comment]
the fix for #56 was hard coding a fix for the 2022.7 version. the quick fix would be to change line [130](https://github.com/oziee/ha-solcast-solar/blob/f91b0077de7951c7958f5b8a546c1c7a73898ad9/custom_components/solcast_solar/coordinator.py#L130) and [146](https://github.com/oziee/ha-solcast-solar/blob/f91b0077de7951c7958f5b8a546c1c7a73898ad9/custom_components/solcast_solar/coordinator.py#L146) to 2022.8. however, it is probably better to require version 2022.7 or higher and take out the if statements.

**Comment by swa72** [comment]
Could this be a related side effect? 

https://github.com/home-assistant/core/issues/76279

**Comment by oziee** [comment]
yeah there was hard coded code that only checked for v2022.7.. now that 2022.8 came out it didn't match:)

changed the code to now work.. new code will only work with HA 2022.7+

**Comment by swa72** [comment]
Thanks, new version fixed it :-)
